// <auto-generated />
using CMS.DAL.Models.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CMS.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240407210018_secondMig")]
    partial class secondMig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CMS.DAL.Models.Entities.AbnormalOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("Reasons")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubReasons")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("AbnormalOrders");
                });

            modelBuilder.Entity("CMS.DAL.Models.Entities.OrderInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<float>("BillingAmount")
                        .HasColumnType("real");

                    b.Property<float>("BillingFeeInKG")
                        .HasColumnType("real");

                    b.Property<string>("BillingStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("ItemWeightKG")
                        .HasColumnType("real");

                    b.Property<int>("NumberOfItem")
                        .HasColumnType("int");

                    b.Property<string>("OrderNote")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOfItem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WayBillStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("OrderInfos");
                });

            modelBuilder.Entity("CMS.DAL.Models.Entities.ReceiverInfo", b =>
                {
                    b.Property<int>("ReceiverID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReceiverID"));

                    b.Property<string>("ReceiverCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverCountry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReceiverPhoneNumber")
                        .HasColumnType("int");

                    b.Property<string>("ReceiverRegion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverStreet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReceiverID");

                    b.ToTable("ReceiverInfos");
                });

            modelBuilder.Entity("CMS.DAL.Models.Entities.SenderInfo", b =>
                {
                    b.Property<int>("SenderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SenderID"));

                    b.Property<string>("SenderCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderCountry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SenderPhoneNumber")
                        .HasColumnType("int");

                    b.Property<string>("SenderRegion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderStreet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SenderID");

                    b.ToTable("SenderInfos");
                });

            modelBuilder.Entity("ReceiverInfoSenderInfo", b =>
                {
                    b.Property<int>("ReceiversReceiverID")
                        .HasColumnType("int");

                    b.Property<int>("ReceiversSenderID")
                        .HasColumnType("int");

                    b.HasKey("ReceiversReceiverID", "ReceiversSenderID");

                    b.HasIndex("ReceiversSenderID");

                    b.ToTable("ReceiverInfoSenderInfo");
                });

            modelBuilder.Entity("CMS.DAL.Models.Entities.AbnormalOrder", b =>
                {
                    b.HasOne("CMS.DAL.Models.Entities.OrderInfo", "OrderInfo")
                        .WithOne("AbnormalOrder")
                        .HasForeignKey("CMS.DAL.Models.Entities.AbnormalOrder", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderInfo");
                });

            modelBuilder.Entity("CMS.DAL.Models.Entities.OrderInfo", b =>
                {
                    b.HasOne("CMS.DAL.Models.Entities.ReceiverInfo", "ReceiverInfo")
                        .WithMany("OrderInfos")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CMS.DAL.Models.Entities.SenderInfo", "SenderInfo")
                        .WithMany("OrderInfos")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReceiverInfo");

                    b.Navigation("SenderInfo");
                });

            modelBuilder.Entity("ReceiverInfoSenderInfo", b =>
                {
                    b.HasOne("CMS.DAL.Models.Entities.ReceiverInfo", null)
                        .WithMany()
                        .HasForeignKey("ReceiversReceiverID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CMS.DAL.Models.Entities.SenderInfo", null)
                        .WithMany()
                        .HasForeignKey("ReceiversSenderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CMS.DAL.Models.Entities.OrderInfo", b =>
                {
                    b.Navigation("AbnormalOrder");
                });

            modelBuilder.Entity("CMS.DAL.Models.Entities.ReceiverInfo", b =>
                {
                    b.Navigation("OrderInfos");
                });

            modelBuilder.Entity("CMS.DAL.Models.Entities.SenderInfo", b =>
                {
                    b.Navigation("OrderInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
